# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += memchr.c
SRC += memcmp.c
SRC += memcpy.S
SRC += memmove.S
SRC += memset.S
SRC += strcat.c
SRC += strchr.c
SRC += strcmp.c
SRC += strcoll.c
SRC += strcpy.c
SRC += strcspn.c
SRC += strerror.c
SRC += strlen.c
SRC += strncat.c
SRC += strncmp.c
SRC += strncpy.c
SRC += strpbrk.c
SRC += strrchr.c
SRC += strspn.c
SRC += strstr.c
SRC += strtok.c
SRC += strxfrm.c
SRC += syserr1.c
SRC += syserr2.c
SRC += syserr3.c

# For _FORTIFY_SOURCE
SRC += memcpyf.c
SRC += memmovef.c
SRC += memsetf.c
SRC += strcatf.c
SRC += strcpyf.c
SRC += strncatf.c
SRC += strncpyf.c
SRC += strxfrmf.c

include $(TOP)/../makefile.inc
