# Copyright (C) 2014 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 2013 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += dprintf.c
SRC += fdopen.c
SRC += fileno.c
SRC += popen.c
SRC += vdprintf.c

# For _FORTIFY_SOURCE
SRC += dprintff.c
SRC += vdprntff.c

include $(TOP)/../makefile.inc
