# Copyright (C) 2002 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += imaxabs.c
SRC += imaxdiv.c
SRC += strimax.c
SRC += strumax.c
SRC += wcsimax.c
SRC += wcsumax.c

include $(TOP)/../makefile.inc
