# Copyright (C) 2023 Ray Chason, see COPYING.DJ for details
TOP=../..

SRC += mbrtoc16.c # mbrtoc16
SRC += c16rtomb.c # c16rtomb
SRC += mbrtoc32.c # mbrtoc32
SRC += c32rtomb.c # c32rtomb

include $(TOP)/../makefile.inc
