# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += ctime.c
SRC += difftime.c
SRC += strftime.c
SRC += time.c

# For _FORTIFY_SOURCE
SRC += strftimf.c

include $(TOP)/../makefile.inc
