# Copyright (C) 2002 DJ Delorie, see COPYING.DJ for details
# Copyright (C) 1994 DJ Delorie, see COPYING.DJ for details
TOP=../..

SRC += chrdata.c
SRC += iswalnum.c
SRC += iswalpha.c
SRC += iswblank.c
SRC += iswcntrl.c
SRC += iswdigit.c
SRC += iswgraph.c
SRC += iswlower.c
SRC += iswprint.c
SRC += iswpunct.c
SRC += iswspace.c
SRC += iswupper.c
SRC += iswxdigit.c
SRC += iswctype.c
SRC += wctype.c
SRC += towlower.c
SRC += towupper.c
SRC += towctrans.c
SRC += wctrans.c

include $(TOP)/../makefile.inc
