/* data table generated by chrdata.rb */
/* cntrl is defined as general category Cc */
static struct chr_range const cntrl[] = {
    { 0x0000, 0x001F },
    { 0x007F, 0x009F },
    { 0x2028, 0x2029 }
};
