# Copyright (C) 2020 Ray Chason, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

# Analogues to string.h
SRC += wmemchr.c
SRC += wmemcmp.c
SRC += wmemcpy.S
SRC += wmemmove.S
SRC += wmemset.S
SRC += wcscat.c
SRC += wcschr.c
SRC += wcscmp.c
SRC += wcscoll.c
SRC += wcscpy.c
SRC += wcscspn.c
SRC += wcslen.c
SRC += wcsncat.c
SRC += wcsncmp.c
SRC += wcsncpy.c
SRC += wcspbrk.c
SRC += wcsrchr.c
SRC += wcsspn.c
SRC += wcsstr.c
SRC += wcstok.c
SRC += wcsxfrm.c

# Analogues to stdlib.h
SRC += wcstod.c
SRC += wcstof.c
SRC += wcstol.c
SRC += wcstold.c
SRC += wcstoll.c
SRC += wcstoul.c
SRC += wcstoull.c

# Analogue to time.h
SRC += wcsftime.c

# Multibyte conversions
SRC += codepage.c
SRC += btowc.c
SRC += mbrlen.c
SRC += mbsinit.c
SRC += mbrtowc.c
SRC += wcrtomb.c
SRC += wctob.c
SRC += mbsrtowcs.c
SRC += wcsrtombs.c

include $(TOP)/../makefile.inc
