# Copyright (C) 2020, 2023 Ray Chason, see COPYING.DJ for details
# Copyright (C) 1995 DJ Delorie, see COPYING.DJ for details
TOP=../..

# Analogues to string.h
SRC += wmemchr.c
SRC += wmemcmp.c
SRC += wmemcpy.S
SRC += wmemmove.S
SRC += wmemset.S
SRC += wcscat.c
SRC += wcschr.c
SRC += wcscmp.c
SRC += wcscoll.c
SRC += wcscpy.c
SRC += wcscspn.c
SRC += wcslen.c
SRC += wcsncat.c
SRC += wcsncmp.c
SRC += wcsncpy.c
SRC += wcspbrk.c
SRC += wcsrchr.c
SRC += wcsspn.c
SRC += wcsstr.c
SRC += wcstok.c
SRC += wcsxfrm.c

# Analogues to stdio.h
SRC += fgetwc.c
SRC += getwc.c
SRC += getwchar.c
SRC += fgetws.c
SRC += ungetwc.c
SRC += fputwc.c
SRC += putwc.c
SRC += putwchar.c
SRC += fputws.c
SRC += dowprnt.c
SRC += fwprintf.c
SRC += swprintf.c
SRC += wprintf.c
SRC += vfwprntf.c
SRC += vswprntf.c
SRC += vwprintf.c
SRC += dowscan.c
SRC += fwscanf.c
SRC += swscanf.c
SRC += wscanf.c
SRC += vfwscanf.S
SRC += vswscanf.c
SRC += vwscanf.c

# Analogues to stdlib.h
SRC += wcstod.c
SRC += wcstof.c
SRC += wcstol.c
SRC += wcstold.c
SRC += wcstoll.c
SRC += wcstoul.c
SRC += wcstoull.c

# Analogue to time.h
SRC += wcsftime.c

# Multibyte conversions
SRC += codepage.c
SRC += btowc.c
SRC += mbrlen.c
SRC += mbsinit.c
SRC += mbrtowc.c
SRC += wcrtomb.c
SRC += wctob.c
SRC += mbsrtowcs.c
SRC += wcsrtombs.c

# Other
SRC += fwide.c

# For _FORTIFY_SOURCE
SRC += fwprntff.c
SRC += swprntff.c
SRC += vfwprtff.c
SRC += vswprtff.c
SRC += vwprntff.c
SRC += wprintff.c
SRC += fgetwsf.c
SRC += wcscatf.c
SRC += wcscpyf.c
SRC += wcsncatf.c
SRC += wcsncpyf.c
SRC += wcsxfrmf.c
SRC += wmemcpyf.c
SRC += wmemmovf.c
SRC += wmemsetf.c
SRC += wcsftimf.c
SRC += wcrtombf.c
SRC += mbwc1f.c
SRC += wcmb1f.c

include $(TOP)/../makefile.inc
