# Copyright (C) 2020 Ray Chason, see COPYING.DJ for details
TOP=../..

SRC += feclrexc.S # feclearexcept
SRC += fegteflg.S # fegetexceptflag
SRC += ferseexc.S # feraiseexcept
SRC += festeflg.S # fesetexceptflag
SRC += fetstexc.S # fetestexcept
SRC += fegetrnd.S # fegetround
SRC += fesetrnd.S # fesetround
SRC += fegetenv.S # fegetenv
SRC += fehldexc.S # feholdexcept
SRC += fesetenv.S # fesetenv
SRC += feupdenv.S # feupdateenv
SRC += fedflenv.S # __dj_fe_dfl_env

include $(TOP)/../makefile.inc
